apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: cert-manager
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: 1.19.2
    chart: cert-manager
    helm:
      releaseName: cert-manager
      valuesObject:
        installCRDs: true
  syncPolicy:
    {{- toYaml .Values.argocd.autoSyncPolicy | nindent 8 }}
